export type PackageCategory = "ecommerce" | "smm" | "sem" | "dropshipping";

export interface PackageFeature {
  text: string;
  heading?: boolean;
}

export interface Package {
  category: PackageCategory;
  slug: string;
  title: string;
  description: string;
  price: string;
  comparePrice: string;
  monthly?: boolean;
  priceNotes?: string[];
  features: PackageFeature[];
  popupCat: "web" | "dropshipping";
}

function f(text: string, heading = false): PackageFeature {
  return { text, heading };
}

const packages: Package[] = [
  {
    category: "ecommerce",
    slug: "beginner",
    title: "Beginner Shopify",
    description:
      "Revolutionize your online presence with our Shopify website design services.",
    price: "$249",
    comparePrice: "$498",
    popupCat: "web",
    features: [
      f("Theme-based Design"),
      f("Up-To 10 Products"),
      f("Dedicated Designer & Developer"),
      f("Unlimited Revisions"),
      f("100% Satisfaction Guarantee"),
      f("100% Unique Design Guarantee"),
    ],
  },
  {
    category: "ecommerce",
    slug: "growth",
    title: "Growth Shopify",
    description:
      "Create dream Shopify website with our expert design and development services.",
    price: "$599",
    comparePrice: "$1198",
    popupCat: "web",
    features: [
      f("Customized Design"),
      f("1 Month Free Shopify Subscription"),
      f("Up-To 50 Products"),
      f("Mini Shopping Cart Integration"),
      f("Payment Module Integration"),
      f("Dedicated Designer & Developer"),
      f("Unlimited Revisions"),
      f("100% Satisfaction Guarantee"),
      f("100% Unique Design Guarantee"),
    ],
  },
  {
    category: "ecommerce",
    slug: "levelup",
    title: "Level Up Shopify",
    description:
      "Transform your online presence with our Shopify web design services.",
    price: "$999",
    comparePrice: "$1998",
    popupCat: "web",
    features: [
      f("Customized Design"),
      f("2 Month Free Shopify Subscription"),
      f("Up-To 75 Products"),
      f("Full Shopping Cart Integration"),
      f("Payment Module Integration"),
      f("Easy Product Search"),
      f("Dedicated Designer & Developer"),
      f("Unlimited Revisions"),
      f("100% Satisfaction Guarantee"),
      f("100% Unique Design Guarantee"),
    ],
  },
  {
    category: "ecommerce",
    slug: "professional",
    title: "Pro Shopify",
    description: "Build Shopify store easily with our professional services.",
    price: "$1499",
    comparePrice: "$2998",
    popupCat: "web",
    features: [
      f("Customized Design"),
      f("3 Month Free Shopify Subscription"),
      f("Up-To 125 Products"),
      f("Full Shopping Cart Integration"),
      f("Payment Module Integration"),
      f("Easy Product Search"),
      f("Product Reviews"),
      f("Blog Page"),
      f("5 Promotional Banners"),
      f("Team Of Expert Designers Developers"),
      f("Unlimited Revisions"),
      f("100% Satisfaction Guarantee"),
      f("100% Unique Design Guarantee"),
    ],
  },
  {
    category: "ecommerce",
    slug: "executive",
    title: "Executive Shopify",
    description:
      "Effortlessly set up Shopify store with the help of our experts.",
    price: "$2499",
    comparePrice: "$4998",
    popupCat: "web",
    features: [
      f("Unlimited Pages Website with Unique Design"),
      f("5 Custom Logo Design"),
      f("4 Month Free Shopify Subscription"),
      f("Up-to 250 products"),
      f("FREE Unlimited Revisions"),
      f("Custom Shopping Cart Integration"),
      f("Multiple Payment Module Integration"),
      f("News Letter Subscription"),
      f("Product Ratings & Reviews"),
      f("Blog Page"),
      f("Multiple Currency Support"),
      f("Mobile Responsive"),
      f("Dedicated Team of Expert Designers & Developers"),
      f("Dedicated Project Manager"),
      f("100% Satisfaction Guarantee"),
    ],
  },
  {
    category: "ecommerce",
    slug: "toptier",
    title: "Top Tier Shopify",
    description:
      "Maximize your potential with our expert Shopify store design services.",
    price: "$4999",
    comparePrice: "$9998",
    popupCat: "web",
    features: [
      f("Complete Custom Design & Development"),
      f("5 Month Free Shopify Subscription"),
      f("Unique, User-Friendly, Interactive, Dynamic, High-End UI Design"),
      f("Up-to 500 products (Option To Scale)"),
      f("Unlimited Banner Designs"),
      f("Interactive Sliding Banners"),
      f("Special Hover Effects"),
      f("Client/User Dashboard Area"),
      f("Customized Contact Us Form"),
      f("Multiple Filtration Option (Search by Age, Experience, Talent, Industry etc.)"),
      f("Custom Coding and Development"),
      f("Online Appointment/Scheduling integration (Optional)"),
      f("Online Payment Integration"),
      f("Invoicing System"),
      f("Automated Email Notifications"),
      f("Multi-lingual (Optional)"),
      f("Complete Database Creation"),
      f("Signup Area (For Newsletters, Offers, etc.)"),
      f("Search Engine Submission"),
      f("Mobile Responsive"),
      f("Master Admin Panel"),
      f("Complete Deployment"),
      f("Dedicated Team of Designers and Developers"),
    ],
  },
  {
    category: "smm",
    slug: "startup",
    title: "Startup",
    description: "Attract More Leads",
    price: "$550",
    comparePrice: "$1100",
    monthly: true,
    popupCat: "web",
    features: [
      f("Prior Analysis", true),
      f("Social Media Strategy"),
      f("Social Media Audit"),
      f("Social Recommendations"),
      f("Content Plan Creation"),
      f("12 Posts Per Month"),
      f("5 Graphic Social Posts"),
      f("03 Stories / Highlights"),
      f("02 Carousel Posts"),
      f("Social Platforms Supported", true),
      f("Facebook"),
      f("Instagram"),
      f("Social Media Management", true),
      f("Monthly Social Posts Scheduling"),
      f("Social Pages Cosmetics (Cover Photo, About Section, Display Picture And More)"),
      f("Facebook Business Manager Setup"),
      f("Facebook Pixel Integration"),
      f("Daily Monitoring Of Social Assets"),
      f("Daily Monitoring Of Boosted Posts"),
      f("Features", true),
      f("Dedicated Project Manager"),
      f("24 HR Support, 5 Days A Week"),
      f("Monthly Progress Report"),
    ],
  },
  {
    category: "smm",
    slug: "sme",
    title: "SMM for SME",
    description: "Transform Your Online Store",
    price: "$999",
    comparePrice: "$1998",
    monthly: true,
    popupCat: "web",
    features: [
      f("Prior Analysis", true),
      f("Social Media Strategy"),
      f("Social Media Audit"),
      f("Social Recommendations"),
      f("Content Plan Creation"),
      f("24 Posts Per Month"),
      f("10 Graphic Social Posts"),
      f("05 Stories / Highlights"),
      f("03 Carousel Posts"),
      f("Social Platforms Supported", true),
      f("Facebook"),
      f("Instagram"),
      f("Twitter"),
      f("Social Media Management", true),
      f("Monthly Social Posts Scheduling"),
      f("Social Community Management (Query + Comment Responses)"),
      f("Social Pages Cosmetics (Cover Photo, About Section, Display Picture And More)"),
      f("Facebook Business Manager Setup"),
      f("Facebook Pixel Integration"),
      f("Daily Monitoring Of Social Assets"),
      f("Daily Monitoring Of Boosted Posts"),
      f("Reputation Management (Reviews, Q/A)"),
      f("Facebook Shop Setup"),
      f("Spam Monitoring"),
      f("Social Ads Management", true),
      f("2 Social Ad Platforms"),
      f("Total 2 Campaign Per Month"),
      f("5 Adsets Per Month"),
      f("Ad Spend (Budget Required)"),
      f("Dedicated Ads Expert"),
      f("Features", true),
      f("Dedicated Project Manager"),
      f("24 HR Support, 5 Days A Week"),
      f("Monthly Progress Report"),
    ],
  },
  {
    category: "smm",
    slug: "professional",
    title: "Professional",
    description: "Seamless Store Solutions",
    price: "$1999",
    comparePrice: "$3998",
    monthly: true,
    popupCat: "web",
    features: [
      f("Prior Analysis", true),
      f("Social Media Strategy"),
      f("Social Media Audit"),
      f("Social Recommendations"),
      f("Content Plan Creation"),
      f("36 Posts Per Month"),
      f("20 Graphic Social Posts"),
      f("10 Stories / Highlights"),
      f("07 Carousel Posts"),
      f("03 GIFS Post"),
      f("02 Articles / SEO Blog Posts"),
      f("Social Platforms Supported", true),
      f("Facebook"),
      f("Instagram"),
      f("Linkedin"),
      f("Twitter"),
      f("Pinterest"),
      f("Social Media Management", true),
      f("Monthly Social Posts Scheduling"),
      f("Social Community Management (Query + Comment Responses)"),
      f("Social Pages Cosmetics (Cover Photo, About Section, Display Picture And More)"),
      f("Facebook Business Manager Setup"),
      f("Facebook Pixel Integration"),
      f("Daily Monitoring Of Social Assets"),
      f("Daily Monitoring Of Boosted Posts"),
      f("Reputation Management (Reviews, Q/A)"),
      f("Facebook Shop Setup"),
      f("Target Page Likes & Followers"),
      f("Chatbot Integration"),
      f("Spam Monitoring"),
      f("Social Ads Management", true),
      f("All Social Ad Platforms"),
      f("Unlimited Campaign Per Month"),
      f("Unlimited Adsets Per Month"),
      f("All Ad Objectives Supported"),
      f("Detailed Campaign Monitoring"),
      f("Daily Campaign Optimization"),
      f("Ad Spend (Budget Required)"),
      f("Dedicated Ads Expert"),
      f("Features", true),
      f("Dedicated Project Manager"),
      f("24 HR Support, 5 Days A Week"),
      f("Monthly Progress Report"),
    ],
  },
  {
    category: "sem",
    slug: "essential-sem",
    title: "ESSENTIAL SEM",
    description: "For businesses starting with paid search",
    price: "$550",
    comparePrice: "$1100",
    monthly: true,
    priceNotes: ["+ 10% of ad spend", "Minimum ad spend: $1,500/month"],
    popupCat: "web",
    features: [
      f("Included Campaign Types:", true),
      f("Google Search (Branded + Non-Branded)"),
      f("1 Conversion Goal Setup"),
      f("What's Included:", true),
      f("Full keyword research & competitor analysis"),
      f("Campaign setup & structure"),
      f("Ad copywriting (headlines + descriptions)"),
      f("Extensions setup (callouts, sitelinks, etc.)"),
      f("Conversion tracking setup"),
      f("Negative keyword management"),
      f("Monthly optimization & bid adjustments"),
      f("Monthly performance report"),
      f("Ideal For:", true),
      f("Local businesses, service providers, or brands testing paid search for the first time."),
    ],
  },
  {
    category: "sem",
    slug: "growth-sem",
    title: "GROWTH SEM",
    description: "For scaling ecommerce & service businesses",
    price: "$999",
    comparePrice: "$1998",
    monthly: true,
    priceNotes: ["+ 9% of ad spend", "Minimum ad spend: $3,000/month"],
    popupCat: "web",
    features: [
      f("Included Campaign Types:", true),
      f("Google Search"),
      f("Google Shopping OR Performance Max (choose one)"),
      f("Display Remarketing"),
      f("What's Included:", true),
      f("Everything in Essential, plus:"),
      f("Full creative support (ad copy + asset creation guidance)"),
      f("Shopping feed optimization (if applicable)"),
      f("Audience targeting strategy"),
      f("Remarketing setup"),
      f("Landing page improvement suggestions"),
      f("A/B testing of ads"),
      f("Bi-weekly optimizations"),
      f("Conversion tracking + GA4 integration"),
      f("Detailed monthly reporting + strategy notes"),
      f("Ideal For:", true),
      f("Brands ready to scale revenue and maximize return on ad spend."),
    ],
  },
  {
    category: "sem",
    slug: "scale-dominate-sem",
    title: "SCALE & DOMINATE SEM",
    description: "For aggressive growth & full-funnel domination",
    price: "$1999",
    comparePrice: "$3998",
    monthly: true,
    priceNotes: ["+ 8% of ad spend", "Minimum ad spend: $6,000/month"],
    popupCat: "web",
    features: [
      f("Included Campaign Types:", true),
      f("Search"),
      f("Shopping"),
      f("Performance Max"),
      f("Display Remarketing"),
      f("Discovery"),
      f("Bing Ads"),
      f("(Up to 5 campaign types included)"),
      f("What's Included:", true),
      f("Everything in Growth, plus:"),
      f("Full creative management (headlines, descriptions, asset strategy)"),
      f("Advanced audience layering"),
      f("Multi-campaign budget allocation strategy"),
      f("Full funnel strategy (cold → warm → hot traffic)"),
      f("Ongoing CRO guidance"),
      f("Weekly performance optimizations"),
      f("Competitor monitoring"),
      f("Advanced reporting dashboard"),
      f("Quarterly growth planning session"),
      f("Ideal For:", true),
      f("Ecommerce brands & multi-location businesses looking to dominate their market."),
    ],
  },
  {
    category: "dropshipping",
    slug: "starter",
    title: "Starter",
    description:
      "Transform your online store with our top-tier dropshipping services.",
    price: "$1200",
    comparePrice: "$2400",
    popupCat: "dropshipping",
    features: [
      f("Shopify Store Setup (Basic)"),
      f("Mobile Optimization"),
      f("Legal Pages (Privacy, Refund, TOS)"),
      f("Dropshipping App Integration (Basic - DSers)"),
      f("Product Import & Setup (10 Products)"),
      f("Payment Gateway Setup"),
    ],
  },
  {
    category: "dropshipping",
    slug: "growth",
    title: "Growth",
    description:
      "Improve your business efficiency with our expert dropshipping services.",
    price: "$2500",
    comparePrice: "$5000",
    popupCat: "dropshipping",
    features: [
      f("Shopify Store Setup (Advanced)"),
      f("Mobile Optimization"),
      f("Legal Pages (Privacy, Refund, TOS)"),
      f("Dropshipping App Integration (Best Options)"),
      f("Product Import & Setup (20 Products)"),
      f("Payment Gateway Setup"),
      f("Branded Logo Design (Basic Logo)"),
      f("Custom Home Page Design"),
      f("On-Page SEO Optimization (Basic SEO)"),
      f("Automated Order Fulfillment Setup"),
      f("Email Capture & Basic Popups"),
      f("Social Media Integration (Basic)"),
      f("Post-Launch Support (15 Days)"),
    ],
  },
  {
    category: "dropshipping",
    slug: "pro-brand",
    title: "Pro Brand",
    description:
      "Take your e-commerce business to the next level with our dropshipping expertise.",
    price: "$5000",
    comparePrice: "$10000",
    popupCat: "dropshipping",
    features: [
      f("Shopify Store Setup (Premium Design)"),
      f("Mobile Optimization"),
      f("Legal Pages (Privacy, Refund, TOS)"),
      f("Dropshipping App Integration (Advanced Integrations)"),
      f("Product Import & Setup (40 Products)"),
      f("Payment Gateway Setup"),
      f("Branded Logo Design (Custom Logo)"),
      f("Custom Homepage Design"),
      f("On-Page SEO Optimization (Full SEO)"),
      f("Automated Order Fulfillment Setup"),
      f("Email Capture & Basic Popups"),
      f("Social Media Integration (Full Setup)"),
      f("Post-Launch Support (30 Days)"),
      f("Abandoned Cart Recovery Setup"),
      f("Facebook Pixel & Google Analytics"),
      f("Custom Branding (Color Palette, Fonts, Guidelines)"),
      f("Conversion Boosters (Urgency, Reviews, Trust Badges)"),
      f("Strategy Call (30-Min)"),
    ],
  },
  {
    category: "dropshipping",
    slug: "empire",
    title: "Empire",
    description:
      "Cut costs and boost efficiency with our optimized dropshipping services.",
    price: "$11000",
    comparePrice: "$22000",
    popupCat: "dropshipping",
    features: [
      f("Shopify Store Setup (Custom Premium Build)"),
      f("Mobile Optimization"),
      f("Legal Pages (Privacy, Refund, TOS)"),
      f("Dropshipping App Integration (Private Supplier Setup)"),
      f("Product Import & Setup (100+ Fully Optimized)"),
      f("Payment Gateway Setup"),
      f("Branded Logo Design (Premium Branding Kit)"),
      f("Custom Homepage Design"),
      f("On-Page SEO Optimization (Full SEO + Speed Boost)"),
      f("Automated Order Fulfillment Setup"),
      f("Email Capture & Basic Popups"),
      f("Social Media Integration (Full Setup + Strategy)"),
      f("Post-Launch Support (60 Days + Concierge)"),
      f("Abandoned Cart Recovery Setup"),
      f("Facebook Pixel & Google Analytics"),
      f("Custom Branding (Color Palette, Fonts, Guidelines)"),
      f("Conversion Boosters (Urgency, Reviews, Trust Badges)"),
      f("Strategy Call (60-Min)"),
      f("Brand Domain & Email Setup"),
      f("Premium Apps & Plugin Integrations"),
      f("Free Product Vendors (3-5)"),
      f("Facebook & Google Ad Creatives (Full Funnel Ads)"),
      f("TikTok & Reels Short Videos (5 Branded Shorts)"),
      f("Full Brand Identity & Store Strategy Plan"),
    ],
  },
];

const packageMap = new Map(
  packages.map((pkg) => [`${pkg.category}/${pkg.slug}`, pkg]),
);

export function getPackage(category: string, slug: string): Package | undefined {
  return packageMap.get(`${category}/${slug}`);
}

export function getAllPackagePaths(): { category: string; slug: string }[] {
  return packages.map(({ category, slug }) => ({ category, slug }));
}

export function getPackageHref(category: PackageCategory, slug: string): string {
  return `/packages/${category}/${slug}`;
}
